# Generated by Django 4.1.5 on 2023-02-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_task_created_at_task_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
